# Generated by Django 6.0.6 on 2026-07-25 23:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Lojas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='categorias/')),
                ('ordem', models.PositiveIntegerField()),
                ('ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='Lojas.loja')),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='EstruturaCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('banner', 'BANNER'), ('promocoes', 'PROMOÇÕES'), ('mais_vendidos', 'MAIS VENDIDOS'), ('categorias', 'CATEGORIAS'), ('combos', 'COMBOS'), ('novidades', 'NOVIDADES'), ('recomendados', 'RECOMENDADOS')], max_length=30)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lojas.loja')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='GrupoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('minimo', models.PositiveSmallIntegerField(default=0)),
                ('maximo', models.PositiveSmallIntegerField(default=1)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_adicionais', to='Lojas.loja')),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='GrupoDeSabores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True)),
                ('nome', models.CharField(max_length=60)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_sabores', to='Lojas.loja')),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='Lojas.loja')),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='adicionais/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Cardapio.grupoadicional')),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('tipo', models.CharField(choices=[('SIMPLES', 'Produto Simples'), ('COMBO', 'Combo')], default='SIMPLES', max_length=10)),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('disponivel', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False)),
                ('possui_sabores', models.BooleanField(default=False)),
                ('permite_multiplos_sabores', models.BooleanField(default=False)),
                ('maximo_sabores', models.PositiveSmallIntegerField(default=1)),
                ('tempo_preparo', models.PositiveIntegerField(default=20)),
                ('codigo', models.CharField(blank=True, max_length=30)),
                ('ordem', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='Cardapio.categoria')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='Lojas.loja')),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoComboGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('obrigatorio', models.BooleanField(default=True)),
                ('minimo', models.PositiveSmallIntegerField(default=1)),
                ('maximo', models.PositiveSmallIntegerField(default=1)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_combo', to='Cardapio.produto')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoComboGrupoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Cardapio.produtocombogrupo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cardapio.produto')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex.: Promoção da Semana', max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('preco_promocional', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField()),
                ('ativa', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=True, help_text='Exibir na seção Promoções do cardápio.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocoes', to='Lojas.loja')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocoes', to='Cardapio.produto')),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='sabores/')),
                ('valor_adicional', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sabores', to='Cardapio.grupodesabores')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sabores', to='Lojas.loja')),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoGrupoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='Cardapio.grupoadicional')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_adicionais', to='Cardapio.produto')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('produto', 'grupo'), name='produto_grupo_unico')],
            },
        ),
        migrations.CreateModel(
            name='ProdutoIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permite_remocao', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.CharField(blank=True, max_length=80)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_ingredientes', to='Cardapio.ingrediente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='Cardapio.produto')),
            ],
            options={
                'ordering': ['ordem'],
                'constraints': [models.UniqueConstraint(fields=('produto', 'ingrediente'), name='produto_ingrediente_unico')],
            },
        ),
        migrations.CreateModel(
            name='ProdutoSabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sabores', to='Cardapio.produto')),
                ('sabor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='Cardapio.sabor')),
            ],
            options={
                'ordering': ['ordem'],
                'constraints': [models.UniqueConstraint(fields=('produto', 'sabor'), name='produto_sabor_unico')],
            },
        ),
        migrations.CreateModel(
            name='SaborIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permite_remocao', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.CharField(blank=True, max_length=80)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sabores_ingredientes', to='Cardapio.ingrediente')),
                ('sabor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='Cardapio.sabor')),
            ],
            options={
                'ordering': ['ordem'],
                'constraints': [models.UniqueConstraint(fields=('sabor', 'ingrediente'), name='sabor_ingrediente_unico')],
            },
        ),
    ]
