# Generated by Django 6.0.6 on 2026-07-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cardapio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, max_length=170, unique=True),
        ),
        migrations.AlterField(
            model_name='estruturacardapio',
            name='tipo',
            field=models.CharField(choices=[('banner', 'BANNER'), ('promocoes', 'PROMOÇÕES'), ('mais_vendidos', 'MAIS VENDIDOS'), ('categorias', 'CATEGORIAS'), ('combos', 'COMBOS'), ('novidades', 'NOVIDADES'), ('recomendados', 'RECOMENDADOS')], max_length=30),
        ),
    ]
