# Generated by Django 6.0.6 on 2026-07-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cardapio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupodesabores',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itemadicional',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='adicionais/'),
        ),
    ]
