# Generated by Django 6.0.6 on 2026-08-13 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cardapio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoGrupoSabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='Cardapio.grupodesabores')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_sabores', to='Cardapio.produto')),
            ],
            options={
                'ordering': ['ordem'],
                'constraints': [models.UniqueConstraint(fields=('produto', 'grupo'), name='produto_grupo_sabor_unico')],
            },
        ),
    ]
