# Generated by Django 6.0.6 on 2026-07-09 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cardapio', '0002_grupodesabores_descricao_itemadicional_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('SIMPLES', 'Produto Simples'), ('COMBO', 'Combo')], default='SIMPLES', max_length=10),
        ),
        migrations.CreateModel(
            name='ProdutoComboGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('obrigatorio', models.BooleanField(default=True)),
                ('minimo', models.PositiveSmallIntegerField(default=1)),
                ('maximo', models.PositiveSmallIntegerField(default=1)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_combo', to='Cardapio.produto')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoComboGrupoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Cardapio.produtocombogrupo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cardapio.produto')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
