# Generated by Django 6.0.6 on 2026-08-13 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cardapio', '0002_produtogruposabor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtocombogrupoitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_combo', to='Cardapio.produto'),
        ),
        migrations.AlterField(
            model_name='produtogrupocombo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_combos', to='Cardapio.produtocombogrupo'),
        ),
    ]
