# Generated by Django 6.0.6 on 2026-08-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cardapio', '0003_alter_produtocombogrupoitem_produto_and_more'),
        ('Lojas', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='estruturacardapio',
            constraint=models.UniqueConstraint(fields=('loja', 'tipo'), name='unique_estrutura_cardapio_loja_tipo'),
        ),
    ]
