# Generated by Django 6.0.6 on 2026-08-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cardapio', '0004_estruturacardapio_unique_estrutura_cardapio_loja_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estruturacardapio',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='cardapio/banners/'),
        ),
    ]
