# Generated by Django 6.0.6 on 2026-08-08 14:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cardapio', '0001_initial'),
        ('Lojas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('tipo_entrega', models.CharField(choices=[('ENTREGA', 'Entrega'), ('RETIRADA', 'Retirada'), ('CONSUMO_LOCAL', 'Consumo no local')], default='ENTREGA', max_length=20)),
                ('nome_cliente', models.CharField(max_length=150)),
                ('telefone_cliente', models.CharField(blank=True, max_length=30)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('numero_endereco', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('referencia', models.CharField(blank=True, max_length=150)),
                ('observacao', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='Lojas.loja')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=120)),
                ('descricao_produto', models.TextField(blank=True)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Pedidos.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='Cardapio.produto')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItemAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_adicional', models.CharField(max_length=120)),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('adicional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='Cardapio.itemadicional')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adicionais', to='Pedidos.pedidoitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItemCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo', models.CharField(max_length=80)),
                ('nome_produto', models.CharField(max_length=120)),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='Cardapio.produtocombogrupo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_combo', to='Pedidos.pedidoitem')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_combo_pedido', to='Cardapio.produto')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItemIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ingrediente', models.CharField(max_length=80)),
                ('removido', models.BooleanField(default=True)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='Cardapio.ingrediente')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='Pedidos.pedidoitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItemSabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sabor', models.CharField(max_length=120)),
                ('valor_adicional', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sabores', to='Pedidos.pedidoitem')),
                ('sabor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='Cardapio.sabor')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='Pedidos.pedido')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PedidoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('codigo', models.SlugField(max_length=60)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('aparece_kanban', models.BooleanField(default=True)),
                ('finalizador', models.BooleanField(default=False)),
                ('cancelamento', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_pedidos', to='Lojas.loja')),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='Pedidos.pedidostatus'),
        ),
        migrations.CreateModel(
            name='PedidoStatusHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='Pedidos.pedido')),
                ('status_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historicos_status_anterior', to='Pedidos.pedidostatus')),
                ('status_novo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_status_novo', to='Pedidos.pedidostatus')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_status_pedido', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='pedidostatus',
            index=models.Index(fields=['loja', 'ativo', 'ordem'], name='Pedidos_ped_loja_id_a288f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedidostatus',
            constraint=models.UniqueConstraint(fields=('loja', 'codigo'), name='status_pedido_codigo_unico_por_loja'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['loja', 'status'], name='Pedidos_ped_loja_id_083946_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['loja', 'criado_em'], name='Pedidos_ped_loja_id_0f797c_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(fields=('loja', 'numero'), name='pedido_numero_unico_por_loja'),
        ),
    ]
