# Generated by Django 6.0.6 on 2026-08-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidostatus',
            name='sistema',
            field=models.BooleanField(default=False),
        ),
    ]
