# Generated by Django 6.0.6 on 2026-08-16 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenuitem',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='SubSubMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subitens', to='Interface.submenuitem')),
            ],
        ),
    ]
