# Generated by Django 6.0.6 on 2026-07-03 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lojas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.RemoveField(
            model_name='loja',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='numero',
        ),
        migrations.AddField(
            model_name='loja',
            name='endereco',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loja', to='Lojas.endereco'),
        ),
    ]
